import json
import math
import itertools
import os

def calculate_haversine(lat1, lon1, lat2, lon2):
    """Calculates the great-circle distance between two points on Earth in km."""
    R = 6371.0 # Earth radius in kilometers

    # Convert coordinates to radians
    lat1_rad, lon1_rad = math.radians(lat1), math.radians(lon1)
    lat2_rad, lon2_rad = math.radians(lat2), math.radians(lon2)

    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad

    # The Haversine formula
    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c

def generate_route_network():
    print("Generating Metro Square route distances...")
    
    # 1. Load the coordinates generated by your previous script
    try:
        with open('config/airport_coordinates.json', 'r') as f:
            airports = json.load(f)
    except FileNotFoundError:
        print("Error: airport_coordinates.json not found. Run clean_airports.py first!")
        return

    routes = {}
    
    # 2. The CS Flex: itertools.permutations
    # This automatically creates all 12 directional pairs (e.g., DEL-BOM and BOM-DEL)
    airport_codes = list(airports.keys())
    for origin, dest in itertools.permutations(airport_codes, 2):
        
        lat1, lon1 = airports[origin]['lat'], airports[origin]['lon']
        lat2, lon2 = airports[dest]['lat'], airports[dest]['lon']
        
        distance_km = calculate_haversine(lat1, lon1, lat2, lon2)
        
        # Create a unique route key (e.g., "DEL_BOM")
        route_key = f"{origin}_{dest}"
        routes[route_key] = {
            "origin": origin,
            "destination": dest,
            "distance_km": round(distance_km, 2)
        }

    # 3. Save the final network mapping
    os.makedirs('config', exist_ok=True)
    output_path = 'config/route_distances.json'
    
    with open(output_path, 'w') as f:
        json.dump(routes, f, indent=4)
        
    print(f"Successfully generated {len(routes)} routes!")
    print(f"Saved to {output_path}")

if __name__ == "__main__":
    generate_route_network()